In [41]:
import requests,re,numpy as np
from bs4 import BeautifulSoup

In [42]:
years=[]
titles=[]
run_time=[]
certificate=[]
rating=[]
genre=[]
votes=[]
meta_score = []
gross=[]
director=[]
for i in range(1,11):
#     https://www.imdb.com/list/ls006266261/?st_dt=&mode=detail&page=2&ref_=ttls_vm_dtl&sort=release_date,desc
    url = f'https://www.imdb.com/list/ls006266261/?st_dt=&mode=detail&page={i}&ref_=ttls_vm_dtl&sort=release_date,desc'
    request_header = {'Content-Type': 'text/html; charset=UTF-8','User-Agent': 'Chrome/101.0.0.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0','Accept-Encoding': 'gzip, deflate, br'}
    page = requests.get(url,headers =request_header)
    page.text
    soup = BeautifulSoup(page.text)
#     for j in soup.find_all("div",class_='lister-item-content'):
#         m = j.find("span",class_="metascore favorable")
#         print(m)
#         ppp=m.text
# #         print(m)
#         mp = re.findall("(\d+)",ppp)
# #         print(mp)
#         if mp:
# #             print(mp)
#             meta_score.append(mp[0])
#         else:
#             meta_score.append(np.nan)  
            
    for j in soup.find_all("div",class_='lister-item-content'):
    #     print(i)
    #     print('*'*50)
        all1 = j.find("h3",class_='lister-item-header')
        all2 = all1.text.strip()
    #     print(all2)
        r1 = re.findall('[A-Za-z].+',all2)
        if r1:
            titles.append(r1[0])
        else:
            titles.append(np.nan)

        r2 = re.findall('\((\d+)\)',all2)
        if r2:
            years.append(r2[0])
        else:
            years.append(np.nan)

        c = j.find("span",class_='certificate')
        if c==None:
            certificate.append(np.nan)
        else:
            certificate.append(c.text)

        run_t = j.find("span",class_='runtime')
        r = run_t.text
        r1 = re.findall('(\d+)',r)
#         print(r1)
        if r1:
            run_time.append(r1[0])
        else:
            run_time.append(np.nan)

        ge= j.find("span",class_='genre')
        g = ge.text.strip()
        if g:
            genre.append(g)
        else:
            genre.append(np.nan)

        ra = j.find("span",class_='ipl-rating-star__rating')
        rat = ra.text.strip()
        if rat:
            rating.append(rat)
        else:
            rating.append(np.nan)
        
        
        dir11 = re.findall("Director:\n(\w.+)",j.text)
        if dir11:
            director.append(dir11[0])
        else:
            director.append(np.nan)
        

        grs = re.findall("Gross:\n\$(\d.+)M",j.text)
        if grs:
            gross.append(grs[0])
        else:
            gross.append(np.nan)

            
            
        g = j.find("span",{'name':'nv'})
        if g:
            votes.append(g.text)
        else:
            votes.append(np.nan)    
    
        m = j.find("span", class_="metascore favorable")

        # Check if the element is found
        if m:
            # Extract the text from the found element and remove leading/trailing whitespace
            metascore_text = m.text.strip()

            # Use regular expressions to extract the Metascore value
            mp = re.findall(r"(\d+)", metascore_text)

            if mp:
                # Append the Metascore value to the meta_score list
                meta_score.append(mp[0])
            else:
                # If no Metascore value is found, append NaN
                meta_score.append(np.nan)
        else:
            # If the span element is not found, append NaN
            meta_score.append(np.nan)
#     print(i)

In [27]:
print(len(titles))
print(len(years))
print(len(run_time))
print(len(certificate))
print(len(genre))
print(len(meta_score))
print(len(rating))
print(len(votes))
print(len(director))
print(len(gross))

1000
1000
1000
1000
1000
1000
1000
1000
1000
1000

In [4]:
d = {'Title':titles,'Released_year':years,'run_time':run_time,'rating':rating,'certificate':certificate,'genre':genre,'votes':votes,'meta_score':meta_score,'director':director,'gross':gross}

In [5]:
import pandas as pd
df = pd.DataFrame(d)

In [6]:
df

,Title,Released_year,run_time,rating,certificate,genre,votes,meta_score,director,gross
0,Tenet,2020,150,7.3,UA,"Action, Sci-Fi, Thriller","592,946",69,Christopher Nolan,58.46
1,The Irishman,2019,209,7.8,16,"Biography, Crime, Drama","431,242",94,Martin Scorsese,7.00
2,Uncut Gems,2019,135,7.4,18,"Crime, Drama, Thriller","318,314",93,NaN,NaN
3,Midsommar,2019,148,7.1,A,"Drama, Horror, Mystery","403,598",72,Ari Aster,27.33
4,John Wick: Chapter 3 - Parabellum,2019,130,7.4,A,"Action, Crime, Thriller","425,986",73,Chad Stahelski,171.02
...,...,...,...,...,...,...,...,...,...,...
995,Mr. Smith Goes to Washington,1939,129,8.1,U,"Comedy, Drama","121,413",73,Frank Capra,9.60
996,The Wizard of Oz,1939,102,8.1,U,"Adventure, Family, Fantasy","428,755",92,NaN,2.08
997,Angels with Dirty Faces,1938,97,7.9,NaN,"Crime, Drama, Film-Noir","23,209",NaN,Michael Curtiz,NaN
998,Manhattan Melodrama,1934,93,7.1,NaN,"Crime, Drama, Romance","4,807",NaN,NaN,NaN
999,King Kong,1933,100,7.9,NaN,"Adventure, Horror","90,989",92,NaN,10.00

In [18]:
df.dropna(inplace=True)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Title          999 non-null    object
 1   Released_year  1000 non-null   object
 2   run_time       1000 non-null   object
 3   rating         1000 non-null   object
 4   certificate    927 non-null    object
 5   genre          1000 non-null   object
 6   votes          1000 non-null   object
 7   meta_score     849 non-null    object
 8   director       919 non-null    object
 9   gross          935 non-null    object
dtypes: object(10)
memory usage: 78.3+ KB

In [25]:
df = df.drop(df[df['Released_year'] == 500].index)

In [26]:
df

,Title,Released_year,run_time,rating,certificate,genre,votes,meta_score,director,gross
0,Tenet,2020,150,7.3,U/A,"Action, Sci-Fi, Thriller","592,946",69,Christopher Nolan,58.46
1,The Irishman,2019,209,7.8,16,"Biography, Crime, Drama","431,242",94,Martin Scorsese,7.00
3,Midsommar,2019,148,7.1,A,"Drama, Horror, Mystery","403,598",72,Ari Aster,27.33
4,John Wick: Chapter 3 - Parabellum,2019,130,7.4,A,"Action, Crime, Thriller","425,986",73,Chad Stahelski,171.02
5,Us,2019,116,6.8,A,"Horror, Mystery, Thriller","341,298",81,Jordan Peele,175.08
...,...,...,...,...,...,...,...,...,...,...
974,Shichinin no samurai,1954,207,8.6,U,"Action, Drama","366,935",98,Akira Kurosawa,0.27
978,The Third Man,1949,104,8.1,U,"Film-Noir, Mystery, Thriller","181,869",97,Carol Reed,0.45
988,Casablanca,1942,102,8.5,U,"Drama, Romance, War","606,165",100,Michael Curtiz,1.02
991,Citizen Kane,1941,119,8.3,U/A,"Drama, Mystery","466,077",100,Orson Welles,1.59
995,Mr. Smith Goes to Washington,1939,129,8.1,U,"Comedy, Drama","121,413",73,Frank Capra,9.60

In [32]:
df.drop(df[df['Released_year'] == 500].index, inplace=True)

In [33]:
df['certificate'] = df['certificate'].replace('Not Rated', 'U/A')

In [34]:
df['certificate'] = df['certificate'].replace('UA', 'U/A')

In [36]:
df.to_csv('final_movies.csv')

In [38]:
df.drop(df[df['Released_year'] == 500].index, inplace=True)

In [39]:
df[df['Released_year']==500]

Empty DataFrame
Columns: [Title, Released_year, run_time, rating, certificate, genre, votes, meta_score, director, gross]
Index: []

In [40]:
df.to_csv('movies.csv')